apiVersion: v1
kind: Pod
metadata:
  name: poli-remediator
  labels:
    app: poli-remediator
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: fishy-remediator
      image: fishy-remediator
      imagePullPolicy: Never
      stdin: true
      tty: true
      env:
        - name: API_ENDPOINT
          value: "localhost"
    - name: refeng
      image: refeng
      imagePullPolicy: Never
      env:
        - name: API_ENDPOINT
          value: "localhost"
      ports:
        - containerPort: 5000
    - name: secap
      image: secap
      imagePullPolicy: Never
      ports:
        - containerPort: 6000
    - name: nsf-catalogue
      image: nsf-catalogue
      imagePullPolicy: Never
      ports:
        - containerPort: 8984

---

apiVersion: v1
kind: Service
metadata:
  name: fishy-ecd
spec:
  type: NodePort
  selector:
    app: poli-remediator
  ports:
    - name: refeng-service
      nodePort: 30001
      port: 5000
    - name: secap-service
      nodePort: 30002
      port: 6000
    - name: nsf-catalogue-service
      nodePort: 30003
      port: 8984

